### PR TITLE
Rpi3 and rpi4

### PR DESCRIPTION
**Pull request by Gabee01**
I needed to run this drivers to the rpi3 target, at the Adafruit_Python_DHT, they [use the same driver for rpi3](https://github.com/adafruit/Adafruit_Python_DHT/commit/e1d10e1513c4fff55733f3926c0e3665f407ffc8#diff-866b612c194e04267a330fa469e9049f), [and for rpi 4](https://github.com/adafruit/Adafruit_Python_DHT/commit/f2799f8408a4d3d105d9457fd9222a942bf57394#diff-866b612c194e04267a330fa469e9049f)

This PR adds drivers for rpi3 and rpi4 targets.

### CODE REVIEW

**Comment by Gabee01** [comment]
I tested only for rpi3 and it works fine, but it should be ok for rpi4 as well :)

**Comment by Gabee01** [comment]
Just to clarify, without this, I had no /srv/erlang/lib/nerves_dht-1.1.4/priv/dht file. See [my issue here](https://github.com/Gabee01/autogrow_ex/issues/1)

**Comment by Gabee01** [comment]
And I also enabled the Dallas 1-Wire protocol as described [here](http://www.carstenblock.org/post/project-excelsius/). Not sure if it's mandatory tough. If it is we should say so in the docs

**Comment by visciang** [comment]
Hey @Gabee01 ,
maybe I'm a bit rusty on this library but can you explain how this is supposed to work.

Please look at https://github.com/Gabee01/nerves_dht/blob/master/src/main.c#L4

There shouldn't be any need to duplicate the same C code under `src/rpi3` `src/rpi4`, it's only a matter of correctly identify the platform version (rpi2, 3 ...) and then conditionally include the right `src/rpi...` path

**Comment by Gabee01** [comment]
you're right. I just looked at the [Makefile](https://github.com/visciang/nerves_dht/blob/master/Makefile#L41-L43) and I see your point.  I'm not sure now why I it wasn't compiling with your version

**Pull request closed without merging**
